add csl edit by visual editor on web
taiga4112/jasnaoe_template_typst pull request #16
Opened 2024-09-08 04:57 UTC by y0o0ic

CSLの編集トライしてみようかと思います。（日本語含めて）

[Visual Editor](https://editor.citationstyles.org/visualEditor/)で、一番近そうなNatureのサンプルをもとに作成、細かいところは後でまとめようと思います。

mainしか見えませんし、権限もないので、forkから直接のpull requiestになります。
管理の仕方はお任せします。

2024-09-08 05:00 UTC, taiga4112 commented
はい、ぜひ！！CSLファイルをコミットしてPRを送付してくれればレビューできそうです！！

2024-09-08 13:14 UTC, y0o0ic reviewed
checked by myself

2024-09-08 13:17 UTC, y0o0ic commented
Pull Request するのに、Reviewが必要で1人以上の承認者からレビューがないといけないようです。

PRレビューを自分でやるか、リクエストする必要がありますが、Approveボタンが使えないですね。

権限をいただけますか？

<img width="653" alt="PR review" src="https://github.com/user-attachments/assets/c6bceb04-a347-4453-b0f9-2d2536e80078">

2024-09-09 00:25 UTC, taiga4112 commented
ちなみに、このページがある以上、pull requestの送信はできています。
CSL開発専用のブランチを作ってここで作っていただいたものを試してみます（後ほど

2024-09-09 00:48 UTC, taiga4112 requested changes
@y0o0ic これを真面目に開発しようと思うと、おそらく対象とするbibファイルかyamlファイルが必要になってくると思います。なにか良い例を作成していただき、その後議論を開始するのが良い気がします。

2024-09-09 11:18 UTC, y0o0ic commented
Zoteroから出力したbibファイルを読み込んで、cslファイルを適用してみました。

2024-09-10 00:35 UTC, taiga4112 approved these changes
素敵です！！あとは少しこちらで整えます。
細かいことが気になってしまうタイプ♡ですので

2024-09-10 00:35 UTC, merged

2024-09-10 03:22 UTC, taiga4112 commented
@y0o0ic 一旦ファイルの位置を私の好みに変更して微修正した完成版をfeature/cslブランチにマージしておきました。日本語併記用のissueとブランチは別に立てておきます